default: &default
  adapter: mysql2
  encoding: utf8
  pool: 1
  username: daverooneyca
  password: Chuckers
  socket: /tmp/mysql.sock
  write_timeout: 1
  read_timeout: 1
  connect_timeout: 2
  reconnect: true

development:
  <<: *default
  database: roots-dev
  host: 10.211.55.6

test:
  <<: *default
  database: roots-test
  host: 10.211.55.6

production:
  <<: *default
  database: roots
  host: 10.211.55.6
